# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Path.ls": "showus.ipynb",
         "load_train_meta": "showus.ipynb",
         "load_papers": "showus.ipynb",
         "load_sample_text": "showus.ipynb",
         "clean_training_text": "showus.ipynb",
         "shorten_sentences": "showus.ipynb",
         "find_sublist": "showus.ipynb",
         "tag_sentence": "showus.ipynb",
         "get_ner_data": "showus.ipynb",
         "write_ner_json": "showus.ipynb",
         "kaggle_run_ner": "showus.ipynb",
         "create_knowledge_bank": "showus.ipynb",
         "literal_match": "showus.ipynb",
         "get_ner_inference_data": "showus.ipynb",
         "kaggle_run_ner_predict": "showus.ipynb",
         "run_inference": "showus.ipynb",
         "get_bert_dataset_labels": "showus.ipynb",
         "jaccard_similarity": "showus.ipynb",
         "filter_bert_labels": "showus.ipynb",
         "combine_matching_and_bert": "showus.ipynb"}

modules = ["showus.py"]

doc_url = "https://qAp.github.io/showus/"

git_url = "https://github.com/qAp/showus/tree/{branch}/"

def custom_doc_links(name): return None
