# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Path.ls": "showus.ipynb",
         "load_train_meta": "showus.ipynb",
         "load_papers": "showus.ipynb",
         "AAAsTITLE": "showus.ipynb",
         "ZZZsTITLE": "showus.ipynb",
         "AAAsTEXT": "showus.ipynb",
         "ZZZsTEXT": "showus.ipynb",
         "load_section": "showus.ipynb",
         "load_paper": "showus.ipynb",
         "text2words": "showus.ipynb",
         "clean_training_text": "showus.ipynb",
         "extract_sentences": "showus.ipynb",
         "shorten_sentences": "showus.ipynb",
         "find_sublist": "showus.ipynb",
         "get_ner_classlabel": "showus.ipynb",
         "tag_sentence": "showus.ipynb",
         "get_paper_ner_data": "showus.ipynb",
         "get_ner_data": "showus.ipynb",
         "write_ner_json": "showus.ipynb",
         "load_ner_datasets": "showus.ipynb",
         "batched_write_ner_json": "showus.ipynb",
         "create_tokenizer": "showus.ipynb",
         "tokenize_and_align_labels": "showus.ipynb",
         "remove_nonoriginal_outputs": "showus.ipynb",
         "jaccard_similarity": "showus.ipynb",
         "compute_metrics": "showus.ipynb",
         "get_ner_inference_data": "showus.ipynb",
         "ner_predict": "showus.ipynb",
         "batched_ner_predict": "showus.ipynb",
         "get_paper_dataset_labels": "showus.ipynb",
         "create_knowledge_bank": "showus.ipynb",
         "literal_match": "showus.ipynb",
         "combine_matching_and_model": "showus.ipynb",
         "filter_dataset_labels": "showus.ipynb"}

modules = ["showus.py"]

doc_url = "https://qAp.github.io/showus/"

git_url = "https://github.com/qAp/showus/tree/{branch}/"

def custom_doc_links(name): return None
